services:
- type: pserv
  repo: https://github.com/ymgong66966/agent_deployment_withcare.git

  # Change this to the path containing your Dockerfile
  rootDir: ./python-agent-example-app/Dockerfile

  name: agent-deployment-test
  runtime: docker

  # Free plan is not available for private services
  plan: starter

  # Environment variables are stored in a group
  # created in the Render dashboard.
  # envVars:
  # - fromGroup: agent-deployment-env 
  # region: virginia

  # 300s is the standard allowed maximum. Talk to render.com support if you need this increased.
  maxShutdownDelaySeconds: 300

  # Sane defaults
  scaling:
    minInstances: 1
    maxInstances: 4
    targetCPUPercent: 60
    targetMemoryPercent: 60
version: "1"
envVarGroups:
  - name: agent-deployment-test
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: LIVEKIT_URL
        sync: false
